# -*- coding: utf-8 -*-
"""Свойства.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lwYIvAuQ1-9ZaHeM_pLSGYcVOFETzOKa

## Испытание свойствами и методами
"""

class Data:
    """Класс для описания пакета информации"""
    def __init__(self, data, ip):
        self.data = data  # передаваемые данные (строка)
        self.ip = ip      # IP-адрес назначения

class Server:
    """Класс для описания работы серверов в сети"""
    __ip_counter = 1  # Счетчик для генерации уникальных IP-адресов

    def __init__(self):
        self.buffer = []  # список принятых пакетов (изначально пустой)
        self.ip = Server.__ip_counter  # IP-адрес текущего сервера
        Server.__ip_counter += 1
        self.router = None  # ссылка на роутер, к которому подключен сервер

    def send_data(self, data):
        """Отправка пакета данных через роутер"""
        if self.router:
            self.router.buffer.append(data)

    def get_data(self):
        """Возвращает принятые пакеты и очищает буфер"""
        packets = self.buffer.copy()
        self.buffer.clear()
        return packets

    def get_ip(self):
        """Возвращает IP-адрес сервера"""
        return self.ip


class Router:
    """Класс для описания работы роутера в сети"""
    def __init__(self):
        self.buffer = []  # буфер для хранения пакетов
        self.servers = {}  # словарь подключенных серверов (ip: server)

    def link(self, server):
        """Подключает сервер к роутеру"""
        self.servers[server.get_ip()] = server
        server.router = self

    def unlink(self, server):
        """Отключает сервер от роутера"""
        ip = server.get_ip()
        if ip in self.servers:
            del self.servers[ip]
            server.router = None

    def send_data(self):
        """Отправляет все пакеты из буфера соответствующим серверам"""
        for data in self.buffer:
            if data.ip in self.servers:
                self.servers[data.ip].buffer.append(data)
        self.buffer.clear()